name: Rust

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]

    name: cargo test
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev
        if: contains(matrix.os, 'ubuntu')

      - name: Install deps
        run: |
            choco install pkgconfiglite
            choco install gstreamer gstreamer-devel
        if: contains(matrix.os, 'windows')

      - name: Build
        run: cargo build --locked --verbose
        if: contains(matrix.os, 'ubuntu')


      - name: Run tests
        run: cargo test --locked --verbose
        if: contains(matrix.os, 'ubuntu')

      - name: Build
        run: |
          dir C:/
          dir C:/gstreamer/
          dir C:/gstreamer/1.0/
          dir C:/gstreamer/1.0/x86_64/lib/pkgconfig
          cargo build --locked --verbose
        env:
            PKG_CONFIG: C:/ProgramData/chocolatey/bin/pkg-config.exe
            PKG_CONFIG_PATH: C:/gstreamer/1.0/x86_64/lib/pkgconfig
        if: contains(matrix.os, 'windows')

      - name: Run tests
        run: cargo test --locked --verbose
        env:
            PKG_CONFIG: C:/ProgramData/chocolatey/bin/pkg-config.exe
            PKG_CONFIG_PATH: C:/gstreamer/1.0/x86_64/lib/pkgconfig
        if: contains(matrix.os, 'windows')


